# Generated by Django 4.2.1 on 2023-06-03 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_options_alter_menu_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(default='someone', max_length=50, verbose_name='Your name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 6, 51, 33, 785979, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 3, 6, 51, 37, 962649, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
